name: Air Quality Daily & Real-time Alert

on:
  schedule:
    # รันทุกๆ 20 นาที
    - cron: '*/20 * * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest
    # เพิ่มส่วนนี้เพื่อบังคับให้ใช้ Node.js 24 และลบ Warning ออก
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests pytz pandas

      - name: Run Bot Script
        env:
          AIR4THAI_KEY: ${{ secrets.AIR4THAI_KEY }}
          TMD_DAILY_KEY: ${{ secrets.TMD_DAILY_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python bot.py

      - name: Save Alert History
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add critical_history.json || true
          git commit -m "Update critical status history [skip ci]" || true
          git push || true
